### ISSUE TITLE
Crash with child relationship and SerializesModels

### ISSUE THREAD

**Issue by ghost** [tighten/parental#49]
## What happens

When a child model has a custom relationship, it crashes when sending a notification that uses the `SerializesModels` trait. Only the broadcast channel is concerned, both email and database channels work fine. It happens when the relationship object has been already used or loaded with the `with` method.

## Environment

Laravel 5.8 and Parental 0.7.

## Steps to reproduce

Here is a dummy example.

I have an `Article` parent model, which can either be of type `OriginalArticle` or `SourcedArticle`. Only `SourcedArticle` items have a relationship with the `sources` table.

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use \Tightenco\Parental\HasChildren;

    protected $fillable = ['type'];

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}
```

```php
<?php

namespace App\Models;

class SourcedArticle extends Article
{
    use \Tightenco\Parental\HasParent;

    public function source()
    {
        return $this->hasOne(Source::class, 'id');
    }
}
```

And here is the `Comment` model:

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    public function article()
    {
        return $this->belongsTo(Article::class);
    }
}
```

Now let's say that we want to send a broadcast notification when someone commented a sourced article.

```php
$user->notify(new UserCommentedSourcedArticleNotification($comment));
```

```php
<?php

namespace App\Notifications;

use App\Models\Comment;
use Illuminate\Notifications\Notification;

class UserCommentedSourcedArticleNotification extends Notification
{
    private $comment;

    public function __construct(Comment $comment)
    {
        $this->comment = $comment;
    }

    public function via()
    {
        return ['broadcast'];
    }

    public function toBroadcast()
    {
        return [
            'source_link' => $this->comment->article->source->link
        ];
    }
}
```

Then on sending, this error will happen:

```
Illuminate\Database\Eloquent\RelationNotFoundException
Call to undefined relationship [source] on model [App\Models\Article].
```

## Causes

The problem is that the relationship is not saved correctly on serializing. Instead of keeping the child type of the relationship, the `SerializesModels` trait stores the `article` relation with the parent `Article` type, instead of `SourcedArticle` in that case. After unserializing, it tries to access to a relationship that isn't part of the parent model.

I hope I have been clear enough, thanks for your support!

**Comment by mattstauffer** [comment]
Hey friends! The team at Tighten has taken Parental back over and we're re-opening the issue tracker, but to give us a clean slate, I'm going to close all old issues that remain from when Caleb closed the issue tracker in 2020. If this is still an outstanding concern with the latest version of Parental, please feel free to open a new issue referencing this one.

Thank you!
