### ISSUE TITLE
Can I check the type in another table?

### ISSUE THREAD

**Issue by akmalhazim** [tighten/parental#52]
Hey,

Instead of using the $childColumn, can i implement an own way of checking the type?
I'm using spatie/laravel-permission and it adds the role in another table.

Would appreciate if you can clarify on this.

Warm regards,
Akmal Hazim

**Comment by mattstauffer** [comment]
Hey friends! The team at Tighten has taken Parental back over and we're re-opening the issue tracker, but to give us a clean slate, I'm going to close all old issues that remain from when Caleb closed the issue tracker in 2020. If this is still an outstanding concern with the latest version of Parental, please feel free to open a new issue referencing this one.

Thank you!
