### ISSUE TITLE
Q: Nova child models?

### ISSUE THREAD

**Issue by nea** [tighten/parental#58]
Hey everyone

I read some tickets here and was able to get Parental to work Nova, at least for my parent resource 'Asset'. I have several sub-assets and would like to have separate administration entries for each one, e.g. A extends Asset, B extends Asset etc. and according resources.

But no matter what I do, these always fail to load in Nova. They are show in the main menu, loading them up fails with a JavaScript error in Nova `Cannot read property 'length' of undefined`.

The parent works, but I would rather have it separated, especially as some children have additional fields. Is that possible?

Thanks a lot for any help in advance.

**Comment by mattstauffer** [comment]
Hey friends! The team at Tighten has taken Parental back over and we're re-opening the issue tracker, but to give us a clean slate, I'm going to close all old issues that remain from when Caleb closed the issue tracker in 2020. If this is still an outstanding concern with the latest version of Parental, please feel free to open a new issue referencing this one.

Thank you!
