### ISSUE TITLE
Installation with laravel v 6.2 e 6.3

### ISSUE THREAD

**Issue by olga-demina** [tighten/parental#63]
Hi to everyone! 
Today I've tried to install the package, but had dependency issue with laravel framework version. I managed to install it with framework version  6.0.3, but not with the later ones (neither with 6.2 nore 6.3). 
This is the error I had:
![installationError](https://user-images.githubusercontent.com/56634652/66913347-bf3d7980-f014-11e9-9172-28182e4475ad.jpeg).
![installationError2](https://user-images.githubusercontent.com/56634652/66913346-bf3d7980-f014-11e9-8311-fdc98a3debb3.jpeg)

And this is my composer.json file:
![composer](https://user-images.githubusercontent.com/56634652/66913408-da0fee00-f014-11e9-8e14-af76b815516f.jpeg)

**Comment by huubvdw** [comment]
This was already fixed with #62, but was not included in the 0.8 tagged release. 

The latest 0.9 tagged release includes this fix, so if you try again you should be fine.

**Comment by mattstauffer** [comment]
Hey friends! The team at Tighten has taken Parental back over and we're re-opening the issue tracker, but to give us a clean slate, I'm going to close all old issues that remain from when Caleb closed the issue tracker in 2020. If this is still an outstanding concern with the latest version of Parental, please feel free to open a new issue referencing this one.

Thank you!
