### ISSUE TITLE
Multiple types for the same user

### ISSUE THREAD

**Issue by shadoWalker89** [tighten/parental#69]
Hi,
This is very nice package but for my app a user can have more then one role, a user can be an `editor` and a `reviewer` for example.
In my `users` table i have a `roles` field that is a `SET`
Is it possible to make this package support multiple roles.

**Comment by leemcd56** [comment]
This would be a nice feature to have. Ideally, it could use a `types` table and have a `user_types` pivot table allowing a user to have multiple types. In addition, each associated type on the pivot table could have a `meta` column for additional data.

I have a situation where this is needed and currently have 12 different user types that is taking up a lot of space in the app.

**Comment by mattstauffer** [comment]
Hey friends! The team at Tighten has taken Parental back over and we're re-opening the issue tracker, but to give us a clean slate, I'm going to close all old issues that remain from when Caleb closed the issue tracker in 2020. If this is still an outstanding concern with the latest version of Parental, please feel free to open a new issue referencing this one.

Thank you!
