### ISSUE TITLE
Eager loading issue :(

### ISSUE THREAD

**Issue by hexatex** [tighten/parental#73]
I have a parent model called **Category**, and two category types, **Link** & **Dynamic**. Only one of them has the relationship **criteriable()**

When I try to load like,
```php
$categories->load('criteria');
```

I get the error, `Call to undefined relationship [criteria] on model [App\Models\Category\Category]'` Is eager loading that relationship possible?

**Category**
```php
class Category extends Model
{
    use Filtered, HasChildren;

    /**
     * @var array
     */
    protected $childTypes = [
        'dynamic' => Dynamic::class,
        'link' => Link::class,
        'regular' => Regular::class,
    ];

    /**
     * @var array
     */
    protected $fillable = [
        'type',
        'name',
    ];
```

**Dynamic**
```php
class Dynamic extends Category implements CategoryType, Criteriable
{
    use HasParent;

    /**
     * Criteria
     * @return MorphOne
     */
    public function criteria()
    {
        return $this->morphOne(Criteria::class, 'criteriable');
    }
```

**Link**
```php
class Link extends Category implements CategoryType
{
    use HasParent;

    /*
     * No relationships
     */
```

**Comment by hexatex** [comment]
I have added 

```php
protected $with = ['criteria'];
```

but that did not work either, no error, just didn't load.

**Comment by hexatex** [comment]
:,(

**Comment by mattstauffer** [comment]
Hey friends! The team at Tighten has taken Parental back over and we're re-opening the issue tracker, but to give us a clean slate, I'm going to close all old issues that remain from when Caleb closed the issue tracker in 2020. If this is still an outstanding concern with the latest version of Parental, please feel free to open a new issue referencing this one.

Thank you!
