### ISSUE TITLE
Set attributes on child Models

### ISSUE THREAD

**Issue by AniketMagadum** [tighten/parental#74]
I have created a Admin model which is the child of the User Model

```php
class Admin extends User
{
    use \Parental\HasParent;

    protected $fillable = ['contact'];
}
```
I have a extra attribute for the Admin model called contact and have also created a migration for the same

```php
Schema::create('admins', function (Blueprint $table) {
   $table->bigIncrements('id');
   $table->string('contact');
   $table->timestamps();
});
```
But when I am trying to insert the attribute, a entry is created in the users table but there is no entry in the admins table. I am not understanding how can I add custom attributes to child models. This is the code I am writing to create a Admin Record
```php
 App\Admin::create([
   'name'=> "Aniket Magadum",
   "email" => "aniket.magadum@sts.in",
   "password" => "password",
   "contact" => "8286000000"
 ]);
```

**Comment by roni-estein** [comment]
I'm no expert I was just reading this package to see what it did, but this is an STI (Single Table Inheritance) package as I understand it so you are not going to make another 'admins' table you are going to add contact to you users table. Then use users for BOTH you users and admins

**Comment by mattstauffer** [comment]
Hey friends! The team at Tighten has taken Parental back over and we're re-opening the issue tracker, but to give us a clean slate, I'm going to close all old issues that remain from when Caleb closed the issue tracker in 2020. If this is still an outstanding concern with the latest version of Parental, please feel free to open a new issue referencing this one.

Thank you!
