### ISSUE TITLE
Laravel notification users

### ISSUE THREAD

**Issue by nathanczachur** [tighten/parental#79]
Is there any documentation on sending a notification to a "child" model?

I am using Parental, without the "type" column on the parent. When I do this:
```php
// The "parent"
class User extends Model
{
    use \Illuminate\Notifications\Notifiable
}
```

```php
// The "child"
class Admin extends User
{
    use \Parental\HasParent;
}
```

```php
$admin = Admin::first();

$admin->notify(new DatabaseNotification);
```

Laravel database notifications store a notifiable_id and notifiable_type in the database.

I would expect the notifiable_type to be \App\User, but in this case, its \App\Admin.

Is this intended behaviour? If so, has anyone been able to get the notification_type column to be \App\User?

**Comment by nathanczachur** [comment]
The issue is arising on a morphMany relationship:
```php
        return $this->morphMany(DatabaseNotification::class, 'notifiable')->orderBy('created_at', 'desc');
```

I think it must be the \Parental\HasParent getMorphClass method not returning the parent class.

**Comment by mattstauffer** [comment]
Hey friends! The team at Tighten has taken Parental back over and we're re-opening the issue tracker, but to give us a clean slate, I'm going to close all old issues that remain from when Caleb closed the issue tracker in 2020. If this is still an outstanding concern with the latest version of Parental, please feel free to open a new issue referencing this one.

Thank you!
